### ISSUE TITLE
filter out inactive users in the network

### ISSUE THREAD

**Issue by TheRakeshPurohit** [shaung/ipmsg#2]
i am using IP Messenger For Win version 4.99r11 on windows 10. How to filter out inactive members of my network.

**Comment by shaung** [comment]
This package does not support ipmsg 3.x or above. Pls feel free to fork this repo, you can refer to https://ipmsg.org/en/ for more information.
(I've been not using IP Messenger for a long time -- not quite sure about changes of the protocol over those years)
